Repository blockful/anticapture, pull requests merged in 2025-07, with the labels that each got.

#1000 feat: enhance indexer schema with commit/branch support and improve event handling
  apps/api-gateway/meshrc.ts
  apps/indexer/package.json
  apps/indexer/src/api/docs.ts
  apps/indexer/src/api/index.ts
  apps/indexer/src/env.ts
  apps/petition/.env.example
  apps/petition/.gitignore
  apps/petition/Dockerfile
  apps/petition/drizzle.config.ts
  apps/petition/drizzle/0000_perpetual_bishop.sql
  apps/petition/drizzle/meta/0000_snapshot.json
  apps/petition/drizzle/meta/_journal.json
  apps/petition/entrypoint.sh
  apps/petition/package.json
  apps/petition/src/client/index.ts
  apps/petition/src/client/votingPower.ts
  apps/petition/src/config.ts
  apps/petition/src/index.ts
  apps/petition/src/middlewares/enum.ts
  apps/petition/src/repositories/index.ts
  apps/petition/src/repositories/postgres.ts
  apps/petition/src/repositories/schema.ts
  apps/petition/src/routes.ts
  apps/petition/src/services/index.ts
  apps/petition/src/services/petition.spec.ts
  apps/petition/src/services/petition.ts
  apps/petition/src/types.ts
  apps/petition/tsconfig.json
Labels: enhancement

#1025 CI/CD w/ zero downtime
  .github/workflows/deploy-indexer.yaml
  infra/indexer/Dockerfile.api
  infra/indexer/Dockerfile.indexer
  infra/indexer/railway.indexer.toml
Labels: enhancement

#1036 Refactor/controllers endpoints to remove dao id parameter
  apps/indexer/src/api/controller/assets.controller.ts
  apps/indexer/src/api/controller/governance-activity/controller.ts
  apps/indexer/src/api/controller/historical-onchain.controller.ts
  apps/indexer/src/api/controller/proposals-activity.controller.ts
  apps/indexer/src/api/controller/token-distribution/controller.ts
  apps/indexer/src/api/controller/token-historical-data.controller.ts
  apps/indexer/src/api/index.ts
  apps/indexer/src/api/middlewares/errorHandler.ts
  apps/indexer/src/api/middlewares/index.ts
  apps/indexer/src/api/middlewares/restValidator.ts
  apps/indexer/src/api/services/coingecko/coingecko.service.ts
  apps/indexer/src/api/services/coingecko/types.ts
  apps/indexer/src/api/services/dune/dune.service.ts
  apps/indexer/src/api/services/historical-balances/historical-balances.service.ts
  apps/indexer/src/api/services/historical-voting-power/historical-voting-power.service.ts
  apps/indexer/src/index.ts
Labels: refactor, enhancement

#1080 avoid deploy indexer on api changes
  .github/workflows/deploy-indexer.yaml
Labels: enhancement

#1083 Clean script
  apps/api-gateway/package.json
  apps/dashboard/package.json
  apps/graphql-client/documents/delegationHistoryCount.graphql
  apps/indexer-metrics/package.json
  apps/indexer/package.json
  package.json
  packages/graphql-client/package.json
  packages/local-node/package.json
  turbo.json
Labels: enhancement

#1107 Data Tables hotfix
  .github/workflows/deploy-indexer.yaml
  apps/dashboard/shared/dao-config/ens.ts
  apps/dashboard/shared/dao-config/uni.ts
  apps/indexer/src/api/index.ts
Labels: hotfix

#1072 fix: op dao config new
  apps/dashboard/app/[daoId]/page.tsx
  apps/dashboard/features/attack-profitability/components/AttackCostBarChart.tsx
  apps/dashboard/features/attack-profitability/hooks/useTopTokenHolderNonDao.ts
  apps/dashboard/features/dao-overview/components/QuorumCard.tsx
  apps/dashboard/shared/components/cards/BaseCardDaoInfo.tsx
  apps/dashboard/shared/components/dropdowns/HeaderDAOSidebarDropdown.tsx
  apps/dashboard/shared/dao-config/arb.ts
  apps/dashboard/shared/dao-config/dao-addresses.ts
  apps/dashboard/shared/dao-config/ens.ts
  apps/dashboard/shared/dao-config/op.ts
  apps/dashboard/shared/dao-config/types.ts
  apps/dashboard/shared/dao-config/uni.ts
  apps/dashboard/shared/hooks/useDaoData.ts
  packages/graphql-client/documents/token-holder/GetDaoAddressesAccountBalances.graphql
  packages/graphql-client/generated.ts
  packages/graphql-client/types.ts
Labels: feature

#1082 Feat/1043 faq
  apps/dashboard/app/faq/page.tsx
  apps/dashboard/features/donation/components/DonationCard.tsx
  apps/dashboard/features/donation/types/index.ts
  apps/dashboard/features/faq/FaqSection.tsx
  apps/dashboard/features/faq/components/FaqCard.tsx
  apps/dashboard/features/faq/components/index.ts
  apps/dashboard/features/faq/index.ts
  apps/dashboard/features/faq/utils/faq-constants.tsx
  apps/dashboard/features/governance-implementation/components/GovernanceImplementationCard.tsx
  apps/dashboard/shared/components/accordions/AccordionContentArea.tsx
  apps/dashboard/shared/components/accordions/index.ts
  apps/dashboard/shared/components/containers/TheSectionLayout.tsx
  apps/dashboard/shared/components/design-system/blank-state/BlankState.tsx
  apps/dashboard/shared/components/design-system/buttons/TheButton.tsx
  apps/dashboard/shared/components/index.ts
  apps/dashboard/shared/components/ui/card.tsx
Labels: feature

#1108 Data Table fixes
  .eslintignore
  .husky/pre-commit
  .vscode/launch.json
  apps/dashboard/features/holders-and-delegates/components/DelegateDelegationHistoryTable.tsx
  apps/dashboard/features/holders-and-delegates/components/DelegateProposalsActivity.tsx
  apps/dashboard/features/holders-and-delegates/components/DelegatesDelegationHistory/VotingPowerVariationGraph.tsx
  apps/dashboard/features/holders-and-delegates/components/ProposalsTable.tsx
  apps/dashboard/features/holders-and-delegates/hooks/useDelegateDelegationHistory.ts
  apps/dashboard/features/holders-and-delegates/hooks/useDelegateDelegationHistoryGraph.ts
  apps/indexer/package.json
  apps/indexer/ponder.schema.ts
  apps/indexer/src/api/controller/proposals-activity.controller.ts
  apps/indexer/src/api/repositories/proposals-activity.repository.ts
  apps/indexer/src/api/services/proposals-activity/proposals-activity.service.ts
  apps/indexer/src/eventHandlers/delegation.ts
  apps/indexer/src/eventHandlers/transfer.ts
  apps/indexer/src/eventHandlers/voting.ts
  compose.yaml
  package.json
  packages/graphql-client/generated.ts
  packages/graphql-client/types.ts
  pnpm-lock.yaml
Labels: hotfix

#1134 fix: adjust daily bucket metrics and truncate timestamp time
  apps/indexer/src/eventHandlers/shared.ts
Labels: bug

#1078 Feat/op integration
  apps/dashboard/app/[daoId]/page.tsx
  apps/dashboard/features/attack-profitability/components/AttackCostBarChart.tsx
  apps/dashboard/features/attack-profitability/components/MultilineChartAttackProfitability.tsx
  apps/dashboard/features/attack-profitability/hooks/useTopTokenHolderNonDao.ts
  apps/dashboard/features/dao-overview/DaoOverviewSection.tsx
  apps/dashboard/features/dao-overview/components/DaoInfoDropdown.tsx
  apps/dashboard/features/dao-overview/components/QuorumCard.tsx
  apps/dashboard/features/dao-overview/components/StageRequirementsTooltip.tsx
  apps/dashboard/features/dao-overview/components/StagesDaoOverview.tsx
  apps/dashboard/features/dao-overview/components/TextCardDaoInfoItem.tsx
  apps/dashboard/features/dao-overview/components/TimelockCard.tsx
  apps/dashboard/features/governance-implementation/components/GovernanceImplementationCard.tsx
  apps/dashboard/features/holders-and-delegates/components/BalanceHistory.tsx
  apps/dashboard/features/holders-and-delegates/components/DelegateDelegationHistoryTable.tsx
  apps/dashboard/features/panel/components/PanelTable.tsx
  apps/dashboard/features/resilience-stages/ResilienceStagesSection.tsx
  apps/dashboard/features/resilience-stages/components/StageAccordion.tsx
  apps/dashboard/features/resilience-stages/components/StageTag.tsx
  apps/dashboard/features/show-support/hooks/usePetition.ts
  apps/dashboard/shared/components/cards/BaseCardDaoInfo.tsx
  apps/dashboard/shared/components/cards/RiskLevelCardSmall.tsx
  apps/dashboard/shared/components/cards/StagesCardRequirements.tsx
  apps/dashboard/shared/components/cards/SwitchCardDaoInfoItem.tsx
  apps/dashboard/shared/components/containers/TheSectionLayout.tsx
  apps/dashboard/shared/components/design-system/alerts/inline-alert/InlineAlert.tsx
  apps/dashboard/shared/components/dropdowns/HeaderDAOSidebarDropdown.tsx
  apps/dashboard/shared/components/ui/table.tsx
  apps/dashboard/shared/constants/mocked-data/mocked-attack-cost-bar-data.ts
  apps/dashboard/shared/dao-config/arb.ts
  apps/dashboard/shared/dao-config/dao-addresses.ts
  apps/dashboard/shared/dao-config/ens.ts
  apps/dashboard/shared/dao-config/op.ts
  apps/dashboard/shared/dao-config/types.ts
  apps/dashboard/shared/dao-config/uni.ts
  apps/dashboard/shared/dao-config/utils.ts
  apps/dashboard/shared/hooks/useDaoData.ts
  apps/dashboard/shared/types/enums/Stage.ts
  apps/dashboard/shared/utils/chain.ts
  apps/dashboard/widgets/HeaderDAOSidebar.tsx
  packages/graphql-client/documents/token-holder/GetDaoAddressesAccountBalances.graphql
  packages/graphql-client/generated.ts
  packages/graphql-client/types.ts
Labels: feature

#1073 [Feature Branch] Additional Pages
  README.md
  apps/dashboard/app/donate/page.tsx
  apps/dashboard/app/faq/page.tsx
  apps/dashboard/app/glossary/page.tsx
  apps/dashboard/features/attack-profitability/components/MultilineChartAttackProfitability.tsx
  apps/dashboard/features/donation/DonationSection.tsx
  apps/dashboard/features/donation/components/DonationCard.tsx
  apps/dashboard/features/donation/components/FundingSourcesCard.tsx
  apps/dashboard/features/donation/components/index.ts
  apps/dashboard/features/donation/index.ts
  apps/dashboard/features/donation/types/index.ts
  apps/dashboard/features/donation/utils/donation-constants.ts
  apps/dashboard/features/donation/utils/index.ts
  apps/dashboard/features/faq/FaqSection.tsx
  apps/dashboard/features/faq/components/FaqCard.tsx
  apps/dashboard/features/faq/components/index.ts
  apps/dashboard/features/faq/index.ts
  apps/dashboard/features/faq/utils/faq-constants.tsx
  apps/dashboard/features/glossary/components/GlossaryContent.tsx
  apps/dashboard/features/glossary/components/GlossaryKeyboard.tsx
  apps/dashboard/features/glossary/components/GlossarySearch.tsx
  apps/dashboard/features/glossary/components/GlossarySearchResults.tsx
  apps/dashboard/features/glossary/glossary.ts
  apps/dashboard/features/glossary/index.ts
  apps/dashboard/features/governance-implementation/components/GovernanceImplementationCard.tsx
  apps/dashboard/features/show-support/hooks/usePetition.ts
  apps/dashboard/public/donation-qr-code.svg
  apps/dashboard/shared/components/accordions/AccordionContentArea.tsx
  apps/dashboard/shared/components/accordions/index.ts
  apps/dashboard/shared/components/buttons/BottomNavigationButtons.tsx
  apps/dashboard/shared/components/buttons/CopyAndPasteButton.tsx
  apps/dashboard/shared/components/cards/BaseCardDaoInfo.tsx
  apps/dashboard/shared/components/design-system/SearchField.tsx
  apps/dashboard/shared/components/design-system/blank-state/BlankState.tsx
  apps/dashboard/shared/components/design-system/buttons/TheButton.tsx
  apps/dashboard/shared/components/index.ts
  apps/dashboard/shared/components/ui/card.tsx
  apps/dashboard/shared/components/wallet/ConnectWallet.tsx
  apps/dashboard/shared/constants/sections-constants.ts
  apps/dashboard/widgets/HeaderDAOSidebar.tsx
  apps/dashboard/widgets/HeaderMobile.tsx
  apps/dashboard/widgets/HeaderSidebar.tsx
  package.json
Labels: feature
